name: Docker Image CI

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build ./utilities/docker/livegeppetto/ --file ./utilities/docker/livegeppetto/Dockerfile --tag livegeppetto:0.4.2
      # run: docker build ./utilities/docker/wormsim/ --file ./utilities/docker/wormsim/Dockerfile --tag wormsim:0.2.6
